# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '0.12.3'
          
      - task: TerraformTaskV1@0
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'AzureDevOps'
          backendAzureRmResourceGroupName: 'IaC'
          backendAzureRmStorageAccountName: 'tfstatefilelocation'
          backendAzureRmContainerName: 'tfstatefile'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTaskV1@0
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
      - task: Prisma Cloud IaC Scan@3
        inputs:
          Path: '.'
          prismaCloudService: 'PrismaCloud-AzureDevOps'
          High: '1'
          Medium: '1'
          Low: '1'
          Operator: 'or'
          Tags: 'repo:TerraformWithAzureDevOps'
  - stage: deploy
    jobs:
    - deployment: deploy_terraform
      continueOnError: false
      environment: 'dev'
      strategy:
       runOnce:
         deploy:
            steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: '0.12.3'
              - task: TerraformTaskV1@0
                displayName: 'init'
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: 'AzureDevOps'
                  backendAzureRmResourceGroupName: 'IaC'
                  backendAzureRmStorageAccountName: 'tfstatefilelocation'
                  backendAzureRmContainerName: 'tfstatefile'
                  backendAzureRmKey: 'terraform.tfstate'         
              - task: TerraformTaskV1@0
                displayName: 'plan'
                inputs:
                  provider: 'azurerm'
                  command: 'plan'
                  environmentServiceNameAzureRM: 'AzureDevOps'
              - task: TerraformTaskV1@0
                displayName: 'apply'
                inputs:
                  provider: 'azurerm'
                  command: 'apply'
                  environmentServiceNameAzureRM: 'AzureDevOps'